version: 2
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: gengjiawen/android-ndk:android-ndk-r16b
    steps:
      - checkout
      - run:
          name: Envinfo
          command: |
            npm i -g envinfo && envinfo
      - run:
          name: Build
          command: |
            apt update && apt install libncurses5 -y


workflows:
  version: 2
  build_and_test:
    jobs:
      - test