version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - run:
          name: Publish Test
          command: | 
            cd matrix/matrix-android
            touch local.properties
            ./gradlew publishToMavenLocal
      - run:
          name: Build Sample Test
          command: | 
            cd samples/sample-android
            touch local.properties
            ./gradlew assembleDebug -PcompileWithSrc=true


workflows:
  version: 2.1
  publishTest:
    jobs:
      - build:
          filters:
            branches:
              only: master
