version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: android/android
    steps:
      - checkout
      - run:
          name: Envinfo
          command: |
            set +e && npm i -g envinfo && envinfo
      - run:
          name: Build
          command: |
            set +e && apt update && apt install libncurses5 -y
            set +e && cd ./matrix/matrix-android
            set +e && ./gradlew assemble
#      - run:
#          name: Check
#          command: |
#            ./gradlew checkstyle

  build:
    executor: android/android
    steps:
      - checkout
      - run:
          name: Publish Test
          command: | 
            cd matrix/matrix-android
            touch local.properties
            ./gradlew publishToMavenLocal
      - run:
          name: Build Sample Test
          command: | 
            cd samples/sample-android
            touch local.properties
            ./gradlew assembleDebug -PcompileWithSrc=true


workflows:
  version: 2.1
  publishTest:
    jobs:
      - test
      - build:
          filters:
            branches:
              only: master
