version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - run:
          name: Publish Test
          command: | 
            cd matrix/matrix-android
            ./gradlew publishToMavenLocal

workflows:
  version: 2.1
  buildapk-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
